services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: REDACTED
      MYSQL_USER: REDACTED
      MYSQL_PASSWORD: REDACTED
      MYSQL_ROOT_PASSWORD: REDACTED
    volumes:
      - ./MovieDb.sql:/docker-entrypoint-initdb.d/MovieDb.sql
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306

  chromadb:
    image: chromadb/chroma
    restart: always
    environment:
      CHROMADB_STORAGE_DIR: /vec_data
    volumes:
      - chromadb_data:/vec_data
    ports:
      - "8000:8000"
    expose:
      - 8000

  flask:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://movienotes:REDACTED@db/MovieDb
    volumes:
      - ./app:/app
    ports:
      - "5001:5001"
    depends_on:
      - db
      - chromadb

volumes:
  db:
  chromadb_data: