services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: MovieDb
      MYSQL_USER: movienotes
      MYSQL_PASSWORD: filipe
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./MovieDb.sql:/docker-entrypoint-initdb.d/MovieDb.sql
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306

volumes:
  db:
