services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: MovieDb
      MYSQL_USER: movienotes
      MYSQL_PASSWORD: filipe
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./MovieDb.sql:/docker-entrypoint-initdb.d/MovieDb.sql
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306

  chromadb:
    image: chromadb/chroma
    restart: always
    environment:
      CHROMADB_STORAGE_DIR: /vec_data
    volumes:
      - chromadb_data:/vec_data
    ports:
      - "8000:8000"
    expose:
      - 8000

  flask:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://movienotes:filipe@db/MovieDb
    volumes:
      - ./app:/app
    ports:
      - "5001:5001"
    depends_on:
      - db
      - chromadb

  nextjs:
    build:
      context: ./interface
      dockerfile: Dockerfile
    volumes:
      - ./interface:/app
    ports:
      - "3000:3000"
    depends_on:
      - flask

volumes:
  db:
  chromadb_data: