services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: movienotes
      MYSQL_USER: movienotes
      MYSQL_PASSWORD: filipe
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./MovieDb.sql:/docker-entrypoint-initdb.d/MovieDb.sql
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db:
