services:
  nextjs:
    image: registry.gitlab.unige.ch/courses1/pt1/2324/g4/nextjs:amd64
    environment:
      NEXT_PUBLIC_API_URL: http://nginx
    ports:
      - "3000:3000"
    depends_on:
      - flask
      - nginx
    networks:
      - app_network
    expose:
      - 3000

  flask:
    image: registry.gitlab.unige.ch/courses1/pt1/2324/g4/flask:amd64
    restart: always
    environment:
<<<<<<< HEAD
      AUTHORIZED_ORIGIN: 'http://10.25.10.22:3000'
      CHROMADB_URI: chromadb
      CHROMADB_STORAGE_DIR: /vec_data
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://movienotes:REDACTED@db/MovieDb
      JWT_SECRET_KEY: "v3ry_s3cr3t_k3y"
      HOST: flask
=======
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://movienotes:REDACTED@db/MovieDb
      - CHROMADB_URI=http://chromadb:8000
      - CHROMADB_STORAGE_DIR=/vec_data
    #env_file:
    #  - .env
    volumes:
      - ./app:/app
>>>>>>> parent of 34666f3 (Fix db et variables d'env)
    ports:
      - "5001:5001"
    depends_on:
      - db
      - chromadb
    networks:
      - app_network

  nginx:
    image: registry.gitlab.unige.ch/courses1/pt1/2324/g4/cors:latest
    ports:
      - "8090:80"
    depends_on:
      - flask
    networks:
      - app_network

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: REDACTED
      MYSQL_USER: REDACTED
      MYSQL_PASSWORD: REDACTED
      MYSQL_ROOT_PASSWORD: REDACTED
    volumes:
      - /home/Lip/g4/MovieDb.sql:/docker-entrypoint-initdb.d/MovieDb.sql
      - db:/var/lib/mysql
    networks:
      - app_network

  chromadb:
    image: chromadb/chroma
    restart: always
    environment:
      CHROMADB_STORAGE_DIR: /vec_data
    volumes:
      - /home/Lip/g4/vec_data:/chroma/chroma
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    networks:
      - app_network

volumes:
  db:

networks:
  app_network:
    driver: bridge
