services:
  nextjs:
    image: registry.gitlab.unige.ch/courses1/pt1/2324/g4/nextjs:x86_64
    environment:
      NEXT_PUBLIC_API_URL: color-movie-flask:5001
    ports:
      - "3000:3000"
    depends_on:
      - flask
    networks:
      - app_network
    expose:
      - 3000

  flask:
    image: registry.gitlab.unige.ch/courses1/pt1/2324/g4/flask:x86_64
    restart: always
    environment:
      AUTHORIZED_ORIGIN: "nextjs:3000"
      CHROMADB_URI: chromadb
      CHROMADB_STORAGE_DIR: /vec_data
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://movienotes:filipe@db/MovieDb
      HOST: flask
    ports:
      - "5001:5001"
    depends_on:
      - db
      - chromadb
    networks:
      - app_network

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: MovieDb
      MYSQL_USER: movienotes
      MYSQL_PASSWORD: filipe
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/Lip/g4/MovieDb.sql:/docker-entrypoint-initdb.d/MovieDb.sql
      - db:/var/lib/mysql
    networks:
      - app_network

  chromadb:
    image: chromadb/chroma
    restart: always
    environment:
      CHROMADB_STORAGE_DIR: /vec_data
    volumes:
      - /home/Lip/g4/vec_data:/chroma/chroma
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    networks:
      - app_network

volumes:
  db:
  chromadb:

networks:
  app_network:
    driver: bridge
